package project.Controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

import groovy.lang.Grab;
import project.Database.User;
import project.Repositories.UserRepository;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/login") // This means URL's start with /carDrive
public class LoginController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	/*@GetMapping(path = "/validate")
	public @ResponseBody ModelAndView validateUser(@RequestParam String email, @RequestParam String password) {
		ModelAndView modelAndView = new ModelAndView();
		modelAndView.setViewName("index");
		User u = userRepository.findByEmail(email);
		System.out.println(u);

		if (u != null) {
			String p = String.valueOf(u.getPassword());
			if (p.equals(password)) {
				modelAndView.setViewName("main");
			}
			return modelAndView;
		} else {
			return modelAndView;
		}

	}*/

}