package project;

import java.sql.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestMethod;



import project.User;
import project.UserRepository;
import project.CarDetails;
import project.CarDetailsRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/carDrive") // This means URL's start with /carDrive
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	private CarDetailsRepository carDetailsRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String firstName,@RequestParam String lastName, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setFirstName(firstName);
		n.setLastName(lastName);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path="/homepage")
	public String homepage() {
		//model.addAttribute("name", name);
		return "homepage";
	}

	@GetMapping(path="/homepage/searchresults")
    public String recoverPass(@RequestParam("q") String username, Model model) {
        //do smthin
        //model.addAttribute("queryresult", "TEST" );
        System.out.println("HERE");
        System.out.println(username);
        CarDetails cd = new CarDetails();
       //cd.setYear("2000");
       //carDetailsRepository.save(cd);

        //User n = new User();
        userRepository.deleteAll();



        String test = username;


        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/CarDrive","springuser","4MhWX$A&*9$v");
            //here sonoo is database name, root is username and password
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from car_details WHERE make = 'Toyota'");

            while(rs.next()) {

                String id = rs.getString("vin");
                String firstName = rs.getString("color");
                String lastName = rs.getString("mpg");
                String dateCreated = rs.getString("make");
                String isAdmin = rs.getString("model");
                String numPoints = rs.getString("price");


                // print the results
                System.out.format("%s, %s, %s, %s, %s, %s\n", id, firstName, lastName, dateCreated, isAdmin, numPoints);

                //System.out.println(rs.getString("price"));
                //model.addAttribute("rs", rs);
                cd.setVIN(rs.getString("vin"));
                cd.setColor(rs.getString("color"));
                cd.setMPG(rs.getString("mpg"));
                cd.setMake(rs.getString("make"));
                cd.setModel(rs.getString("model"));
                cd.setPrice(rs.getString("price"));
                cd.setYear(rs.getString("year"));
                //carDetailsRepository.save(cd);

                User n = new User();
                n.setFirstName(rs.getString("vin"));
                userRepository.save(n);

                //con.close();
            }
            model.addAttribute("cd", userRepository.findAll());


        }catch(Exception e){
            System.out.println(e);

        }

        return "bam";
    }

	/*@RequestMapping(value="/carDrive/homepage/signup", method=RequestMethod.GET)
	public String recoverPass(@RequestParam("q") String username) {
		//do smthin
		return  "main";
	}*/


}